<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ContainerBaseImage>mcr.microsoft.com/windows/nanoserver:ltsc2022</ContainerBaseImage>
    <ContainerRuntimeIdentifier>win10-x64</ContainerRuntimeIdentifier>
    <ContainerRegistry>localhost:5000</ContainerRegistry>
    <RootNamespace>aspire_cri_override.App</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
